on:
  push:
    branches: [main]
    
jobs:
  deploy:
    name: Deploy to Ec2 instance
    runs-on: self-hosted
    steps:
      - name: TO EC2 instance
        run: |
          cd /home/ubuntu/ansible/
          ls
          git show -1 --stat > gitlog.txt
      - name: Send email with commit ID
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Codex-Server-New commit on main branch
          to: joedhitya12@gmail.com
          from: joedhitya12@gmail.com
          body: ${{ github.sha }}
          attachments: |
              /home/ubuntu/ansible/gitlog.txt