on:
  push:
    branches: [main]
    
jobs:
  deploy:
    name: Deploy to Ec2 instance
    runs-on: self-hosted
    steps:
      - name: Git pull in specific directory
        run: |
          cd /home/ubuntu/ansible
          git pull origin main